CREATE TABLE T1 (
   ROW_KEY BIGINT  NOT NULL,
   COLUMN_KEY BIGINT  NOT NULL,
   DATA_BLOB VARBINARY(512000),
   LAST_MODIFIED TIMESTAMP,
   CONSTRAINT PK_HASH_T1 PRIMARY KEY (ROW_KEY, COLUMN_KEY)
);
CREATE TABLE T2 (
   ROW_KEY BIGINT  NOT NULL,
   COLUMN_KEY BIGINT  NOT NULL,
   DATA_BLOB VARBINARY(512000),
   LAST_MODIFIED TIMESTAMP,
   CONSTRAINT PK_HASH_T2 PRIMARY KEY (ROW_KEY, COLUMN_KEY)
);
CREATE TABLE defaulttable (
   ROW_KEY BIGINT  NOT NULL,
   COLUMN_KEY BIGINT  NOT NULL,
   DATA_BLOB VARBINARY(512000),
   LAST_MODIFIED TIMESTAMP,
   CONSTRAINT PK_HASH_defaulttable PRIMARY KEY (ROW_KEY, COLUMN_KEY)
);
